version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python source/manage.py makemigrations &&
             python source/manage.py migrate &&
             python source/manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost

